// auth
export const USER_REQUEST = "USER_REQUEST";
export const USER_FAILURE = "USER_FAILURE";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";

// blogs
export const BLOGS_REQUEST = "BLOGS_REQUEST";
export const BLOGS_FAILURE = "BLOGS_FAILURE";
export const GET_BLOGS_SUCCESS = "GET_BLOGS_SUCCESS";
export const POST_BLOGS_SUCCESS = "POST_BLOGS_SUCCESS";
